classdef SecantTests < tests.esercizio5.WithMaxitTestCase
    properties(TestParameter)
        input = { ...
            [ 0.5, 0.1 ], ...
            [ -0.5, -0.1 ], ...
            [ -0.8, -1.0 ], ...
            [ -1.5, -1.2], ...
            [ 1.5, 1.2], ...
            [ 0.8, 1.0 ] ...
        };

        expectedRoot = { ...
            0, ...
            0, ...
            -1.047197551196598, ...
            -1.047197551196598, ...
            1.047197551196598, ...
            1.047197551196598 ...
        };
    end

    properties(Access = protected)
        assertToleranceAmount = 1e-15;
    end

    methods(Access = protected)
        function [result, iterations] = findRoot(this, input)
            [result, iterations] = esercizio5.secant(...
                this.f, ...
                input(1), ...
                input(2), ...
                this.inputTolerance, ...
                this.inputMaxit ...
            );
        end

        function [result, iterations] = findRootWithoutMaxit(this, input)
            [result, iterations] = esercizio5.secant(...
                this.f, ...
                input(1), ...
                input(2), ...
                this.inputTolerance ...
            );
        end
    end

    methods(Test, ParameterCombination = 'sequential')
        function testX0NonNumeric(this)
            this.assertError(...
                @() esercizio5.secant(this.f, '1', 0, this.inputTolerance, this.inputMaxit), ...
                'inputs:X0MustBeNumeric' ...
            );
        end
        
        function testX1NonNumeric(this)
            this.assertError(...
                @() esercizio5.secant(this.f, 1, '0', this.inputTolerance, this.inputMaxit), ...
                'inputs:X1MustBeNumeric' ...
            );
        end

        function testX0AndX1AreEqual(this)
            this.assertError(...
                @() esercizio5.secant(this.f, 1, 1, this.inputTolerance, this.inputMaxit), ...
                'inputs:X0AndX1MustNotBeEqual' ...
            );
        end

        function testToleranceNonNumeric(this)
            this.assertError(...
                @() esercizio5.secant(this.f, 0, 1, '1e-3', this.inputMaxit), ...
                'inputs:ToleranceMustBeNumeric' ...
            );
        end
        
        function testToleranceLessThanZero(this)
            this.assertError(...
                @() esercizio5.secant(this.f, 0, 1, -1e-3, this.inputMaxit), ...
                'inputs:ToleranceMustBePositive' ...
            );
        end
        
        function testToleranceEqualToZero(this)
            this.assertError(...
                @() esercizio5.secant(this.f, 0, 1, 0, this.inputMaxit), ...
                'inputs:ToleranceMustBePositive' ...
            );
        end
        
        function testMaxitNonNumeric(this)
            this.assertError(...
                @() esercizio5.secant(this.f, 0, 1, this.inputTolerance, '100'), ...
                'inputs:MaxitMustBeNumeric' ...
            );
        end
        
        function testMaxitLessThanZero(this)
            this.assertError(...
                @() esercizio5.secant(this.f, 0, 1, this.inputTolerance, -100), ...
                'inputs:MaxitMustBePositive' ...
            );
        end
        
        function testMaxitEqualToZero(this)
            this.assertError(...
                @() esercizio5.secant(this.f, 0, 1, this.inputTolerance, 0), ...
                'inputs:MaxitMustBeAtLeast1' ...
            );
        end
    end
end